# Custom Grafana dashboards, delivered as ConfigMaps rather than through the
# Grafana UI. kube-prometheus-stack enables the grafana dashboard sidecar by
# default (grafana.sidecar.dashboards.enabled: true, label grafana_dashboard),
# so a labelled ConfigMap in the monitoring namespace is picked up and written
# into /tmp/dashboards inside the Grafana pod within a few seconds. No API call,
# no admin token, no Terraform grafana provider.
#
# The reason to do it this way rather than clicking dashboards together in the
# UI: this cluster is destroyed nightly. A UI-built dashboard lives only in
# Grafana's SQLite database, which is on an emptyDir here, so it would not
# survive a single rebuild. As ConfigMaps the dashboards are in git, are applied
# by the same `terraform apply` that builds the cluster, and are reviewable in a
# diff. The 28 dashboards bundled with kube-prometheus-stack stay untouched.
#
# The JSON does not hardcode datasource UIDs. Each dashboard declares a
# templating variable of type "datasource" (ds_prom, and ds_loki on the platform
# board) and every panel references ${ds_prom} / ${ds_loki}. Grafana resolves
# those to whatever the matching datasource is at load time, which matters
# because the Loki datasource UID is generated by
# kubernetes_config_map_v1.grafana_datasource_loki and is not stable across
# rebuilds.

locals {
  grafana_dashboards = {
    app      = "${path.module}/dashboards/app.json"
    platform = "${path.module}/dashboards/platform.json"
  }
}

resource "kubernetes_config_map_v1" "grafana_dashboards" {
  for_each = local.grafana_dashboards

  metadata {
    # Match the naming of kubernetes_config_map_v1.grafana_datasource_loki -
    # same local.name as that resource.
    name      = "${local.name}-grafana-dashboard-${each.key}"
    namespace = kubernetes_namespace_v1.monitoring.metadata[0].name

    labels = {
      # The label the sidecar watches for. Value is arbitrary; "1" is the
      # convention in the chart's own docs.
      grafana_dashboard = "1"
    }

    annotations = {
      # Puts both dashboards in their own folder so they are not mixed in with
      # the bundled ones. Read by the sidecar, not by Grafana directly.
      grafana_folder = "eks-platform"
    }
  }

  data = {
    "${each.key}.json" = file(each.value)
  }

  # The sidecar container only exists once the Grafana pod from this release is
  # running. Creating the ConfigMap first is harmless (the sidecar lists
  # existing ConfigMaps on startup as well as watching for changes), but the
  # ordering makes the dependency explicit rather than incidental.
  depends_on = [helm_release.kube_prometheus_stack]
}
